### PR TITLE
Add Subject Alternative Name support

### PR DESCRIPTION
**Pull request by Alcaro**
The san_state variable feels like wrong solution, but I couldn't find anything better. If you can, I'll be glad to rewrite it.

### CODE REVIEW

**Comment by eduardsui** [comment]
Cool! I'll take a look and then merge it (I think I will need to change the examples).

**Comment by Alcaro** [comment]
Ping?

On a mostly related note, the wildcard handling looks completely off the marks. To start with, there's this part:
```
int tls_certificate_valid_subject(struct TLSCertificate *cert, const char *subject) {
[...]
    const char *wildcard = strchr((const char *)cert->subject, '*');
    if (wildcard) {
        if (!wildcard[0]) {
```
where wildcard will either be NULL, or point to an asterisk. In neither case can that inner block run. Judging by the nearby comments, I think it's intended to be if (!wildcard[1]).

The entire strchr looks wrong; it ignores everything before the asterisk, I doubt it should. Finally, judging by [RFC 6125 § 6.4.3](https://tools.ietf.org/html/rfc6125#section-6.4.3), *.example.com isn't supposed to match either foo.bar.example.com nor example.com, but the code looks like it does.

I'll fix up that function to be more standards complaint tomorrow. Should I put that in this PR, submit another PR (they'd poke the same function, so they'll give merge conflicts), wait for you to deal with this PR, or something else?

**Comment by eduardsui** [comment]
You are right. Thanks. I'll fix it after I finish the DTLS implementation (I hope today).

**Comment by eduardsui** [comment]
It should be fixed now. Thanks for the info!

I will also pull your code, but I need to finish the DTLS implementation, and modify the examples (it breaks at least tlshellowolrd.c).

**Comment by Alcaro** [comment]
Rebased.

And yeah, sorry about that; the TLS* structs aren't in the header, so I thought they're opaque. Fixed.

**Comment by eduardsui** [comment]
I think there is something wrong (tested with letsencrypt certificate):

1.3.2  1.3.1    SEQUENCE
1.3.1.1      SUBJECT ALTERNATIVE NAME(1):
1.3.1.2      SUBJECT ALTERNATIVE NAME(257):
1.3.1.3      SUBJECT ALTERNATIVE NAME(3): 
1.3.1.4      SUBJECT ALTERNATIVE NAME(257):
1.3.1.5      SUBJECT ALTERNATIVE NAME(129):
1.3.1.6      SUBJECT ALTERNATIVE NAME(129):
1.3.1.7      SUBJECT ALTERNATIVE NAME(129):
1.3.1.8      SUBJECT ALTERNATIVE NAME(128): ?║E]0ôQ-≤5αmñeH█z╬Ñàuπa(yσ▒zÑ╒%h&≡∙J
1.3.1.9      SUBJECT ALTERNATIVE NAME(129):

**Comment by eduardsui** [comment]
I've created a new branch (san) for testing this. For most certificates it seems ok, but for others I get random subjects. I think we should keep the subject field, and add unsigned char **san.

**Comment by eduardsui** [comment]
I've added SAN support in master. It works with any certificate.

**Pull request merged**
